- .github/workflows/go.yml
- .github/workflows/release_build.yml
- CHANGELOG.md
- Makefile
- pkg/proxy/doc.go
- pkg/proxy/example_test.go
- pkg/proxy/proxy.go
- pkg/proxy/proxy_test.go
This PR affects only the case when PAC is used. Closes #2 
When PAC is used, each request may or may require an upstream proxy configuration.
This PR makes sure that, if a URL doesn't need an upstream proxy, the previous request upstream configuration is cleared.
> Resolves #2

- internal/logger/logger.go
- pkg/proxy/proxy.go
- pkg/proxy/utils.go
This PR introduces slightly cleaner logging:
- Always log URL and request method (INFO level)
- Log request headers in DEBUG level
- Avoid logging messages that contain only static information, like `logger.Get().Debugln("Request handled by the HTTP handler")`
> Improving proxy logging

- CHANGELOG.md
- cmd/run.go
- internal/logger/logger.go
- internal/logger/logger_test.go
- pkg/proxy/proxy.go
If the log level > INFO, redirect log messages created by the standard library's global logger to the configured proxy logger with `component=standard` and level `DEBUG`
If the log level <= `INFO`, then disable standard logging.
> Redirect standard logs

- pkg/proxy/proxy.go
Info level logging causes Forwarder logging to both console (when it's at info level which happens a lot) and the file.
It could be fixed some other way but the easiest is to just log, at least ,at debug level
> Reducing proxy log level

- internal/logger/logger.go
- internal/logger/logger_test.go
- pkg/proxy/proxy.go
Revert standard log redirect. `RedirectStandardLogs` and `DiscardStandardLogs` may be moved to `sypl`, and called by the downstream library.
> Revert standard log redirect

- .golangci.yml
- CHANGELOG.md
- go.mod
- go.sum
- pkg/proxy/proxy.go
Resolves the issue #10 
It seems that, under certain conditions, the response struct that is passed to the custom logging handler is not allocated.
Nil response [is handled](https://github.com/elazarl/goproxy/blob/ec48516/proxy.go#L126) in goproxy so the forwarder could just let goproxy log the debugging info.
Example:
```
07:56:52.285 GET 127.0.0.1:64756 -> dpm.demdex.net
07:56:52.430 127.0.0.1:64756 <- dpm.demdex.net 200 OK (59 bytes)
07:56:52.608 GET 127.0.0.1:64756 -> beap.gemini.yahoo.com
07:56:52.719 beap.gemini.yahoo.com <- 127.0.0.1:64756 response is empty
```
> response handler panics - resolves issue #10

- go.mod
- go.sum
The latest goproxy fixes https://github.com/elazarl/goproxy/issues/475 .
> Adding SSE support

- CHANGELOG.md
- cmd/run.go
- go.mod
- go.sum
- pkg/proxy/proxy.go
- pkg/proxy/proxy_test.go
Renaming *_CREDENTIAL to *_AUTH env vars to maintain the same naming convention everywhere
> Renaming *_CREDENTIAL to *_AUTH

- .github/workflows/go.yml
- .gitignore
- Makefile
- README.md
This patch set adds `install-dependencies` makefile target that facilitate installation of required development tools.
I piggybacked improvements to makefile that intend to improve readability and conform to best practices for makefiles.
Fixes #24
> install dependencies

- example_test.go
- go.mod
- go.sum
- proxy.go
- proxy_test.go
- userinfo.go
- util.go
- util_test.go
This patchset reimplements goproxy setup so that the proxy is not reconfigured in runtime.
In addition to that it fixes missing / wrong configurations. See commit messages for details.
Fixes #29
Fixes #31
Fixes #74 
Fixes #76
> proxy: fix initialization

- .golangci.yml
- bind/flag.go
- cmd/forwarder/paceval/paceval.go
- cmd/forwarder/pacserver/pacserver.go
- cmd/forwarder/proxy/proxy.go
- cmd/forwarder/root.go
- cmd/forwarder/wrap.go
- config.go
- config_test.go
- dns.go
- fileurl/fileurl.go
- fileurl/fileurl_test.go
- http_proxy.go
- http_proxy_test.go
- http_transport.go
- log.go
- log/stdlog/stdlog.go
- pac/doc.go
- pac/pac.go
- pac/pac_test.go
- pac/testdata/chromium-libpac/ambiguous_entry_point.js
- readurl.go
- tls.go
```
$ forwarder pac-server -h
Start HTTP(S) server that serves a PAC file. The PAC file can be specified as a 
file path or URL with scheme "file", "http" or "https". The PAC file must 
contain FindProxyForURL or FindProxyForURLEx and must be valid. All PAC util 
functions are supported (see below). Alerts are ignored. 
You can start HTTP, HTTPS or H2 (HTTPS) server. The server may be protected by 
basic authentication. If you start an HTTPS server and you don't provide a 
certificate, the server will generate a self-signed certificate on startup.
Usage:
forwarder pac-server --pac <file|url> [--protocol <http|https|h2>] [--address <host:port>] [flags]
Examples:
pac-server --pac pac.js --protocol http --address localhost:8080
pac-server --pac pac.js --protocol https --address …
```
> pac-server and pac-eval subcommands

- .github/workflows/go.yml
- .golangci.yml
- Dockerfile
- Makefile
- cert.go
- cmd/forwarder/httpbin/httpbin.go
- cmd/forwarder/root.go
- dns_test.go
- e2e/.env
- e2e/Makefile
- e2e/args.go
- e2e/client.go
- e2e/docker-compose.yaml
- e2e/httpbin-http.yaml
- e2e/httpbin-https.yaml
- e2e/override/cpuset.yaml
- e2e/override/proxy-http.yaml
- e2e/override/proxy-https.yaml
- e2e/run.sh
- e2e/status_test.go
- httpbin/httpbin.go
- log.go
The e2e tests are implemented using docker-compose, go test, makefile and bash.
There are 4 containers:
- Proxy
- Upstream Proxy
- Test backend (httpbin)
- Test runner
Container configuration is changed by adding environment variables from the override files (see override directory).
This enables to mix and match the files, this could be called a "mixin" model, to enable different features.
All but last container are managed by docker-compose.
On start we wait until all services ready using the readiness check in the api.
The last container is injected to the docker-compose network to run the compiled go test program.
Makefile implements helpers for working with docker and building the test binary.
All the concrete test invocations are done from the run.sh shell script.
The status check …
> e2e testing framework

- cmd/forwarder/proxy/proxy.go
The flags are groupped:
- core
- api
- http
- log
```
Flags:
--protocol                                  HTTP server protocol, one of http, https (env FORWARDER_PROTOCOL) (default http)
--address host:port                         HTTP server listen address in the form of host:port (env FORWARDER_ADDRESS) (default ":3128")
--cert-file string                          HTTP server TLS certificate file (env FORWARDER_CERT_FILE)
--key-file string                           HTTP server TLS key file (env FORWARDER_KEY_FILE)
--read-timeout duration                     HTTP server read timeout (env FORWARDER_READ_TIMEOUT)
--log-http-requests                         log all HTTP requests, by default only responses with status code >= 500 are logged (env FORWARDER_LOG_HTTP_REQUESTS)
--basic-auth …
```
> cmd/forwarder/proxy: group flags by prefix in help view

- config.go
- credentials_test.go
Parsing user:password@host:port string will check if port is '*' and change it to '0'.
Fixes #57
> config: add support for port '*'

- cmd/forwarder/paceval/paceval.go
- cmd/forwarder/pacserver/pacserver.go
The flags are groupped:
- core
- api
- http
- log
Fixes #136
> cmd/forwarder: group flags in help view

- bind/flag.go
- http_proxy.go
- http_server.go
This patch integrates forwarder with timeout changes introduced in https://github.com/saucelabs/martian/pull/1.
> http_server: add read and write timeouts

- bind/flag.go
- e2e/e2e_test.go
- e2e/override/proxy-localhost.yaml
- go.mod
- go.sum
- http_proxy.go
ProxyLocalhost is changed to enum, available values are:
- deny (former false)
- allow (former true)
- direct
In the direct mode requests to localhost are allowed but are not sent to upstream proxy.
Fixes #176
> http_proxy: add ProxyLocalhost=direct mode

- .goreleaser.yml
This patch puts the same `image_templates` values to `docker_manifests` as in `dockers`.
Before this patch goreleaser would make `dockers/image_templates` with {{ .Version }}, but later fail on making `docker_manifests` with **{{ .Tag }}**.
> goreleaser: docker manifests, make image templates use tag or version

- credentials.go
When pac resolves proxy mode to `DIRECT` the url is nil. This would cause panics in `CredentialsMatcher.MatchUrl(nil)`. CredentialsMatcher will now check if url is nil, to avoid nil pointer dereference.
Fixes #192
> credentials: support matching empty urls

- httplog/logger.go
old:
```
2023/01/25 13:58:44 [proxy] INFO:
--------------------------------------------------------------------------------
Request to http://httpbin.org/, status: 200, duration: 627.347375ms
--------------------------------------------------------------------------------
GET http://httpbin.org/ HTTP/1.1
Host: httpbin.org
...
--------------------------------------------------------------------------------
```
new:
```
2023/01/25 13:58:44 [proxy] INFO: GET http://httpbin.org/ status=200 duration=627.347375ms
--------------------------------------------------------------------------------
GET http://httpbin.org/ HTTP/1.1
Host: httpbin.org
...
--------------------------------------------------------------------------------
```
Fixes #198
> httplog: change logging format to more pleasant

- http_proxy.go
- middleware/prometheus.go
This patch implements `martian.RequestResponseModifier` interface for Prometheus object, so that it can gather proxy traffic metrics.
> middleware: use prometheus to gather proxy traffic metrics

- cmd/forwarder/proxy/proxy.go
This patch fixes false example of forwarder proxy where user could specify credentials with comma separated ports. Forwarder does not support comma separated ports in credentials.
> cmd/proxy: fix forwarder proxy usage example

- Dockerfile
- cmd/forwarder/proxy/proxy.go
- e2e/docker-compose.yaml
This patch trims down Docker base image to bare minimum, namely [1]:
* ca-certificates
* /tmp directory
* tzdata
In addition to that
- API server is started by default on localhost:10000, default is moved to cmd
- HEALTHCHECK in Dockerfile is removed
[1] https://github.com/GoogleContainerTools/distroless/blob/main/base/README.md
> dockerfile: use distroless base image

- bind/flag.go
- cmd/forwarder/pacserver/pacserver.go
- cmd/forwarder/proxy/proxy.go
`forwarder help proxy`:
```
Flags:
--protocol                                  HTTP server protocol, one of http, https (env FORWARDER_PROTOCOL) (default http)
--address host:port                         HTTP server listen address in the form of host:port (env FORWARDER_ADDRESS) (default ":3128")
--cert-file string                          HTTP server TLS certificate file (env FORWARDER_CERT_FILE)
--key-file string                           HTTP server TLS key file (env FORWARDER_KEY_FILE)
--read-timeout duration                     HTTP server read timeout (env FORWARDER_READ_TIMEOUT)
--read-header-timeout duration              HTTP server read header timeout (env FORWARDER_READ_HEADER_TIMEOUT) (default 1m0s)
--write-timeout duration                    HTTP server write timeout (env …
```
> cmd,bind: group logging flags together

- .github/workflows/release.yml
- Makefile
- third_party_license.tpl
- third_party_licenses.txt
The licenses are generated with go-licenses tool.
The template is declared in `third_party_license.tpl`
> add third party licenses

- .golangci.yml
- cmd/forwarder/paceval/paceval.go
- credentials.go
- dns.go
- http_proxy.go
- http_server.go
- log/log.go
- pac.go
This patch moves forwarder.Logger into log.Logger. It enables using logger in subpackages without a need to redefine it every time.
> log: ingest Logger interface

- bind/flag.go
- e2e/override/proxy-log.yaml
This patch renames flag to shorter and simpler form.
> bind: rename --log-http-requests to --log-http

- httpbin/httpbin.go
- httpbin/io.go
- httpbin/io_test.go
As random computations are expensive this is a green alternative. It replaces random bloat with and endless "SauceLabs" tapestry.
Fixes #228
> httpbin: do not use rand

- bind/flag.go
New format: 
```
./fwd run --verbose --dns-server=1.2.3.4:53,5.6.7.8:53
2023/03/23 10:34:59 DEBUG: configuration
address=:3128
api-address=localhost:10000
api-basic-auth=
api-cert-file=
api-key-file=
api-log-http=errors
api-protocol=http
api-read-header-timeout=1m0s
api-read-timeout=0s
api-write-timeout=0s
basic-auth=
cert-file=
config-file=
credentials=
dns-server=1.2.3.4:53,5.6.7.8:53
dns-timeout=5s
http-dial-timeout=30s
http-expect-continue-timeout=1s
http-idle-conn-timeout=1m30s
http-keep-alive=30s
http-max-conns-per-host=0
http-max-idle-conns=100
http-max-idle-conns-per-host=11
http-response-header-timeout=0s
http-tls-handshake-timeout=10s
insecure-skip-verify=false
key-file=
log-file=
log-http=errors
pac=
protocol=http
proxy-localhost=deny
read-header-timeout=1m0s
read-timeout=0s …
```
> Improved format of configuration description

- bind/flag.go
- e2e/override/debug.yaml
- log/level.go
- log/stdlog/stdlog.go
This pr replaces verbosity with log levels. Available levels: `error`, `info`, `debug`. Default log level is `info`.
> replace verbosity with log levels

- bind/flag.go
- http_proxy.go
- http_server.go
- tls.go
This moves TLS cert and file configuration for easier reuse.
> http_server: move TLS{Cert,Key}File to TLSConfig

- e2e/e2e_test.go
- e2e/framework.go
- utils/httpexpect/httpexpect.go
Extracting generic httpexpect functionality from forwarder tests makes it usable by other projects. The Client will now take http.RoundTripper, which can be fully customized.
> Move E2E httpexpect Client to its own module

- README.md
Shorthand support for insecure flag has been disabled in be8f5f7.
> fix (readme): remove shorthand for insecure flag

- cmd/forwarder/root.go
- utils/cobrautil/templates/templater.go
This will fix scenarios where envPrefix is different than command name.
> cobrautil (templater): pass custom envPrefix for flag usages

- http_proxy.go
- http_proxy_test.go
Martian has an interwinted logic for setting http.Transport and the dialer. 
Call to SetRoundTripper overwrites tr.DialContext with hp.proxy.dial. 
When hp.transport is a pointer to http.Transport the assignment is visible in the forwarder code. 
The dialer needs to be set first to avoid overwriting.
> fix setting dial function in proxy

- utils/cobrautil/templates/help_flags_printer.go
This patch replaces regexp with manual searching for matching bracket. The regexp implementation is not aware of the brackets semantics and matches the last closing bracket preventing the use of <> and [] later in usage. The current implementation finds the value type definition until the first upper case letter.
> utils/cobrautil/templates: new value type search algorithm

- e2e/dns/db.rpz
- e2e/dns/named.conf.local
- e2e/dns/named.conf.options
- e2e/dns/service.go
- e2e/forwarder/service.go
- e2e/setups.go
- e2e/tests/flag_test.go
- utils/compose/builder.go
- utils/compose/compose.go
- utils/compose/network.go
- utils/compose/service.go
This patch adds: 
- support for defining custom networks in compose tool
- bind9 dns server service to use in e2e tests
- DNS e2e setup
> add DNS e2e tests

- utils/compose/service.go
This is needed for executing commands with root privileges on the container e.g. `iptables`.
> utils/compose(service): enable privileged mode

- e2e/tests/client.go
- utils/httpexpect/httpexpect.go
- utils/httpexpect/trace.go
This allows to inspect the HTTP client events in the test client. It's not enabled by default.
Example:
```
=== RUN   TestProxyGoogleCom
trace.go:19: GetConn for hostPort: proxy:3128
trace.go:38: DNSStart: {Host:proxy}
trace.go:41: DNSDone: {Addrs:[{IP:172.23.0.3 Zone:}] Err:<nil> Coalesced:false}
trace.go:44: ConnectStart: network=tcp, addr=172.23.0.3:3128
trace.go:47: ConnectDone: network=tcp, addr=172.23.0.3:3128, err=<nil>
trace.go:50: TLSHandshakeStart
trace.go:56: TLSHandshakeDone: state={Version:772 HandshakeComplete:true DidResume:false CipherSuite:4865 NegotiatedProtocol:http/1.1 NegotiatedProtocolIsMutual:true ServerName:www.google.com PeerCertificates:[0x40002f2680 0x40002f2c00] VerifiedChains:[[0x40002f2680 0x40002f3180]] SignedCertificateTimestamps:[] OCSPResponse:[] …
```
> utils/httpexpect: add httptrace.ClientTrace

- bind/flag.go
- e2e/forwarder/service.go
- e2e/tests/proxy_test.go
- http_proxy.go
- utils/httpexpect/httpexpect.go
The assert only works for http endpoints.
> assert upstream proxy does the traffic

- bind/flag.go
- httplog/httplog.go
- internal/martian/messageview/messageview.go
A `route` mode is like `url`, but it logs only the host+path to make the logs look thin.
Route log example: 
```
2023/08/28 16:54:40 [proxy] INFO: trace=2 GET www.google.com/ status=200 duration=3.140999458s
```
> Add route mode for http logging 

- bind/describe.go
- bind/describe_test.go
- bind/flag.go
- cmd/forwarder/httpbin/httpbin.go
- cmd/forwarder/pac/server/server.go
- cmd/forwarder/run/run.go
This PR adds an option to describe flags in JSON format.
This is useful for exporting or recording config settings.
> bind: Add JSON parameter to DescribeFlags

- .golangci.yml
> golangci: enable context key type check

- .golangci.yml
- internal/martian/handler.go
- internal/martian/head.go
- internal/martian/httpspec/httpspec_test.go
- internal/martian/proxy.go
We need e2e HEAD test:
* with and without body
* Transfer-Encoding: (none just content-length), chunked, identity
> fix Excess found: excess = 2 url = / (zero-length body) in HEAD response

- utils/cobrautil/bind.go
This trims and reformats string values set from viper. It allows reading yaml and json format lists e.g.
```
dns-server:
- 1.2.3.4
- 4.3.2.1
```
```
{
"dns-server": ["8.8.8.8", "5.5.5.5"]
}
```
and env vars:
```
FORWARDER_DNS_SERVER="1.2.3.4 4.3.2.1" forwarder run
```
It does not affect reading and parsing flags from command line.
> utils/cobrautil: support pasring lists from env vars and config file

- e2e/tests/proxy_test.go
- utils/httpbin/httpbin.go
This adds `/headers` endpoint to httpbin, which returns the incoming request's HTTTP headers.
The test `TestProxyUpstream` has been adjusted to use `/headers`.
> add `/headers` endpoint to httpbin

- bind/flag.go
- e2e/setups.go
- http_proxy.go
- ruleset/ruleset.go
- ruleset/ruleset_test.go
- renaming: `regex.Ruleset` -> `ruleset.Regexp`
- `ruleset.Regexp` returns an error on creation if no include rules are specified
- adjusted unit tests
- adjusted `--deny-domains-exlude` usage description
> Ruleset adjustments

- e2e/Makefile
Before this patch the script would wait until profiling is done and start the benchmark.
> e2e(mk): run profiling concurrently with the benchmark

- cmd/forwarder/run/run.go
- httplog/httplog.go
- internal/martian/context.go
- internal/martian/h2/h2.go
- internal/martian/h2/relay.go
- internal/martian/handler.go
- internal/martian/log/log.go
- internal/martian/mitm/mitm.go
- internal/martian/noop.go
- internal/martian/nosigpipe/nosigpipe_darwin.go
- internal/martian/proxy.go
- internal/martian/proxy_test.go
- log/log.go
- log/stdlog/stdlog.go
Fixes #394 
Example log message:
```
[proxy] [DEBUG] [18a6b0c67a1] msg
```
> refactor recent changes to martian logging

- internal/martian/proxy.go
- internal/martian/proxy_test.go
Wait for the connection to become readable before trying to read the next request.
Fixes #304
> martian: peek the connection before setting read timeout

- utils/cobrautil/bind.go
pflag.FlagSet contains various metadata about the flags e.g. if one has been changed. Using pflag.Flag.Value.Set does not update pflag.FlagSet state.
The flags must be set by FlagSet.Set, otherwise it is easy to violate its internal state.
> utils/cobrautil(bind): set flags directly in FlagSet

- bind/flag.go
- http_proxy.go
- internal/martian/handler.go
- internal/martian/proxy.go
The proxy is capable to associate the request id send in request header with logs.
> Read request ID from header and use in logs

- e2e/forwarder/service.go
- e2e/setups.go
This shortens the `flag-dns-fallback` test.
running setup flag-dns-fallback
--- PASS: TestFlagDNSServer (15.12s)
vs
running setup flag-dns-fallback
--- PASS: TestFlagDNSServer (2.08s)
> e2e: set dns timeout to 1 second

- middleware/prometheus.go
- middleware/testdata/TestPrometheusWrap.golden.txt
Remove host and src metrics labels from http metrics to reduce cardinality
> middleware: remove metrics labels

- cmd/forwarder/run/run.go
- e2e/forwarder/service.go
- e2e/setups.go
- e2e/tests/client.go
- e2e/tests/flag_test.go
- http_proxy.go
- internal/martian/mitm/mitm.go
- utils/httphandler/httphandler.go
> /cacert endpoint

- internal/martian/handler.go
- internal/martian/proxy.go
- internal/martian/proxy_test.go
This adds support for special header "X-Martian-Terminate-TLS". When set to true the proxy will perform TLS handshake before returning the connection.
This has the benefit of using the proxy's TLS configuration for the handshake.
> martian: add TLS termination in CONNECT

- internal/martian/proxy.go
This check prevents the proxy from panic in the following scenario:
1. There isn't any buffered data.
2. Connection goes down.
3. Peek returns an error and nil slice.
4. Checking the first byte to determine a type results in reading from an empty slice.
> martian(mitm): check if peeked data is not nil

- internal/martian/context.go
- log/stdlog/stdlog.go
- Improve request IDs format 
- Log timestamp with microseconds resolution
The logs are as follows:
```
2023/10/05 09:05:16.534433 [proxy] [INFO] no upstream proxy specified
2023/10/05 09:05:16.534436 [proxy] [INFO] localhost proxying mode=deny
2023/10/05 09:05:16.534972 [proxy] [INFO] PROXY server listen address=[::]:3128 protocol=http
2023/10/05 09:05:30.007872 [proxy] [DEBUG] accepted connection from 127.0.0.1:51274
2023/10/05 09:05:30.008515 [proxy] [DEBUG] waiting for request: 127.0.0.1:51274
2023/10/05 09:05:30.013913 [proxy] [DEBUG] [2-9AC543C0] attempting to establish CONNECT tunnel: google.com:443
2023/10/05 09:05:30.013941 [proxy] [DEBUG] [2-9AC543C0] CONNECT to host directly: google.com:443
2023/10/05 09:05:30.082053 [proxy] [INFO] [2-9AC543C0] CONNECT google.com:443 status=200 …
```
> Improve debugging 

- bind/flag.go
As we use this flag in different projects let's not document the default mode in here. The default mode is displayed in the --help either way.
> bind: rephrase `--log-http` usage

- cmd/forwarder/run/run.go
Since we are using a custom registry we need to add Go and process stats. Unfortunately the process data is only available in Linux and Windows.
> cmd/forwarder/run: register process metrics

- cmd/forwarder/root.go
```
Server options:
--address <host:port> (default ':3128') (env FORWARDER_ADDRESS)
The server address to listen on. If the host is empty, the server will listen on all available interfaces.
--basic-auth <username[:password]> (env FORWARDER_BASIC_AUTH)
Basic authentication credentials to protect the server.
-s, --credentials <username[:password]@host:port,...> (env FORWARDER_CREDENTIALS)
Site or upstream proxy basic authentication credentials. The host and port can be set to "*" to match all
hosts and ports respectively. The flag can be specified multiple times to add multiple credentials.
--name <string> (default 'forwarder') (env FORWARDER_NAME)
Name of this proxy instance. This value is used in the Via header in requests. The name value in Via header is
extended with a random string to …
```
> cmd/forwarder: add proxy traffic flag group

- utils/cobrautil/describe.go
- utils/cobrautil/describe_test.go
We add Unredacted option to FlagsDescriber to enable getting the raw values when needed.
This is to support https://github.com/mmatczuk/anyflag/pull/2
> utils/cobrautil: describe flags unredacted

- bind/flag.go
- bind/log.go
- bind/log_test.go
- bind/named.go
- cmd/forwarder/httpbin/httpbin.go
- cmd/forwarder/pac/server/server.go
- cmd/forwarder/run/run.go
- http_proxy.go
- http_server.go
- httplog/httplog.go
- httplog/httplog_test.go
Instead of having separate log-http and api-log-http options, merge them into `--log-http [<module>:]<mode>`
This adds a Config type to `httplog` which contains a map of the module name (used a prefix to the log mode in the CLI) to the log mode:
```go
type Config struct {
ModeOptions []map[string]Mode                                 
defaults    map[string]Mode                                   
}                                                           
```
Examples from the forwarder commands showing the various options of single module, multiple modules, or no modules.
```
$ ./dist/forwarder_linux_amd64_v1/forwarder run --help 2>&1 | grep "log-http "
--log-http [<api>|<proxy>:]<none|short-url|url|headers|body|errors> (env FORWARDER_LOG_HTTP)
$ ./dist/forwarder_linux_amd64_v1/forwarder …
```
> httplog: Merge the log-http and api-log-http CLI options

- e2e/tests/proxy_test.go
- http_proxy_errors.go
Responses will now contain proxy name and error:
First line is a generic message, second the error.
```
curl -x localhost:3128 not.exist   
forwarder failed to connect to remote host
dial tcp: lookup not.exist on 192.168.1.1:53: no such host
```
Header:
```
X-Forwarder-Error: forwarder dial tcp: lookup www on 10.255.3.12:53: no such host
```
> http_proxy: print proxy errors in response body

- e2e/run.go
API servers receive healthcheck requests which pollutes the logs.
> e2e: do not log http in api module while in debug mode

- bind/flag.go
- config.go
```
go run ./cmd/forwarder run --prom-namespace upstream-proxy
Error: invalid argument "upstream-proxy" for "--prom-namespace" flag: invalid namespace: upstream-proxy, it must match "^[a-zA-Z_:][a-zA-Z0-9_:]*$"
See 'forwarder run --help' for usage.
exit status 1
```
> Add prometheus namespace validation 

- cmd/forwarder/root.go
- packaging/config.sh
- utils/cobrautil/config_file.go
This allows to have config files for any subcommand. It also improves command ergonomics ex. go run ./cmd/forwarder/ pac server config-file.
> utils/cobrautil: add funtion to add ConfigFileCommand recursively

- cmd/forwarder/root.go
- utils/cobrautil/config_file.go
- utils/cobrautil/templates/yaml_flag_printer.go
Add section headers and more light to generated default config file.
Example 
```
#
#
#dns-round-robin: false
#
#
#dns-server:
#
#
#dns-timeout: 5s
```
Also, remove config-file flag from default config file
> config file sections

- Makefile
This allows to build devel images with podman.
> mk: allow for custom container runtime in update-devel-image target

- Makefile
This fixes a mistake made in fc05ecd.
> mk: remove excess `--build-arg` from update-devel-image

- .goreleaser.yml
The github-native is based on Pull Requests.
It's now important to provide good PR titles.
> goreleaser: use github-native changelog

- log/stdlog/opts.go
- log/stdlog/stdlog.go
Adding stdlog.WithLabels("foo", "bar")
logger := stdlog.New(c.logConfig, stdlog.WithOnError(onError), stdlog.WithLabels("foo", "bar"))
Produces
```
2023/12/11 12:16:38.145946 [foo] [bar] [proxy] [INFO] no upstream proxy specified
2023/12/11 12:16:38.145949 [foo] [bar] [proxy] [INFO] localhost proxying mode=deny
```
> log/stdlog: add log line labels

- http_proxy.go
One should never set Connection header if not owning the connection. If ran in http2 server setting it causes the whole connection to be closed.
> http_proxy: do not manually set Connection: close header

- dial.go
- dial_unix.go
- dial_windows.go
> dial: use OS defaults for TCP keepalive params

- http_proxy.go
The TLSConfig is not read, it's used in listen and set on construction.
The field is moved above the listener to reflect the creation order.
> http_proxy: unexport HTTPProxy.TLSConfig field

- ruleset/regexp.go
- ruleset/regexp_test.go
This allows to have other parsing mechanisms and still use NewRegexpMatcherFromList().
> ruleset: export RegexpListItem.Exclude

- dialvia/http.go
- dialvia/http_test.go
Add byteReader, a reader that reads only one byte at a time. Wrap connection in byteReader when passing to bufio.NewReaderSize() - bufio is required due to http.ReadResponse() api.
Fixes #616
> dialvia(http): read CONNECT response by byte

- dialvia/http.go
- dialvia/http_test.go
http.ReadResponse() calls bufio.Reader.ReadLine() to read lines. When line fits we can reuse memory and prevent additional allocation and GC.
The status line should fit below 64 bytes:
HTTP/1.1 (8+1 bytes)
Status-Code (3+1 bytes)
Reason-Phrase (<=31 bytes)
CRLF (2 bytes)
Total bytes: 8 + 1 + 3 + 1 + 31 = 44
With 128 bytes we should be able to read most header lines too.
> dialvia(http): change read buffer size to hold response line

- cmd/forwarder/main.go
- command/run/run.go
Setting GOMEMLIMIT has very positive impact on the GC policy. It allows to defer GC til there is less work.
In my tests, using mainly local/browser test, the Heap usage is bellow 40MiB and the system allocated memory bellow 100MiB.
> command/run: add default GOMEMLIMIT

- http_proxy.go
- internal/martian/handler.go
- internal/martian/proxy.go
This patch extracts response writing to separate method and uses isClosedConnError() for smarter error logging like we do in case if readRequest().
CloseAfrerReply is removed for easier refactoring and later function reuse.
> martian: improve error logging in response writing

- e2e/prometheus/service.go
This is to unify the image version with `local/monitoring`.
> e2e/prometheus: use latest image

- internal/martian/proxy.go
Forwarder uses OS TCP keep alive settings, added in 57d08e8.
> martian: dont set tcp keep alive

- packaging/deb/forwarder.postrm
- packaging/rpm/forwarder.postrm
This patch allows to run forwarder purge even if its service-account is missing.
> packaging: removing service account is safe

- bind/flag.go
- http_proxy.go
- internal/martian/proxy.go
- internal/martian/proxy_test.go
- net.go
- net_test.go
- tls.go
This patch adds server side TLS handshake timeout. It will protect forwarders listener and additionally a handshake in mitm. 
Due to the lack of a convenient solution upstream connect is given a constant 1m timeout to complete.
> Add armed Listener with TLS handshake timeout

- api.go
Disable compression and move to new metrics encoding standard if supported to allow frequent allocations for gzip.
Fixes #659
> api(prom): fix allocations made by promhttp

- docs/content/gsoc.md
Make sure your Project Ideas include the ALL of the required information below:
a) a project title/description
b) more detailed description of the project (2-5 sentences) c) expected outcomes
d) skills required/preferred
e) possible mentors
f) expected size of project (90, 175 or 350 hour – yes, 3 options starting in 2024)
> docs/content: update project descriptions with required information

- http_proxy.go
- http_server.go
- net.go
- net_test.go
- prom.go
This would prevent from constructing listener outside forwarder package.
> prom: export config

- internal/martian/proxy_conn.go
- internal/martian/proxy_handler.go
> martian: clear res.Close hop by hop

- command/run/run.go
- log/martianlog/dial.go
> Debug log all dials

- http_proxy_errors.go
Add handleWindowsNetError to handler list directly for simplicity. Adding OS build tags and additional code infrastructure is not worth the effort hance the check is added for all platforms.
Fixes #493
> http_proxy(errors): windows return status 502 for WSAENETUNREACH error

- http_proxy.go
- internal/martian/closewriter.go
- internal/martian/closewriter_test.go
- internal/martian/proxy.go
- internal/martian/proxy_conn.go
- internal/martian/proxy_handler.go
- internal/martian/proxy_trace.go
- middleware/prometheus.go
- middleware/prometheus_test.go
- middleware/testdata/TestPrometheusWrap.golden.txt
> Add request and response size metrics

- net.go
To prevent extended number of t/o errors increase dial t/o by default to 30s.
> dial: increase dial t/o to 30s

- http_proxy.go
- matcher.go
The Matcher interface replaces RegexpMatcher in forwarder's config.
This allows specifying custom match logic for mitm, deny, and direct domains.
> Add matcher interface for domains filtering 

- bind/flag.go
'<' and '>' make a mess in sc docs.
```
-p, --pac <path or URL> (env FORWARDER_PAC)
Proxy Auto-Configuration file to use for upstream proxy selection. It can be a local file or a URL, you can
also use '-' to read from stdin. The data URI scheme is supported, the format is "data:base64,encoded_data".
```
> bind: change data URI scheme format in pac flag usage

- docs/content/cli/forwarder_pac_eval.md
- docs/content/cli/forwarder_pac_server.md
- docs/content/cli/forwarder_ready.md
- docs/content/cli/forwarder_run.md
- docs/content/cli/forwarder_test_grpc.md
- docs/content/cli/forwarder_test_httpbin.md
- utils/docsgen/command.go
SC docs use `id` to organize and structure sidebar. It does not break anything in forwarder.
> docsgen: add ID in the footer for cli 

- utils/docsgen/command.go
> utils/docsgen: export FlagGroups and EnvPrefix variables to allow specifying them

- utils/cobrautil/templates/help_flags_printer.go
- utils/cobrautil/templates/link.go
- utils/cobrautil/templates/markdown_flag_printer.go
This patch implements custom formatting of `<br>`,`<ex>`, and `<link ...>` for help and markdown printers.
> cobrautil/templates: support custom formats in usages 

- docs/content/tutorials/monitoring.md
> docs(monitoring): remove info about --prom-namespace flag

- utils/cobrautil/templates/templater.go
Having --help text go to stderr makes it unusable with tools like grep or less.
According to GNU Coding Standards[1] the --help option should print on standard output.
[1] https://www.gnu.org/prep/standards/html_node/_002d_002dhelp.html
> utils/cobrautil/templates: print help and usage to stdout

- local/linux/Makefile
- packaging/systemd/forwarder.service
Forwarder does not need that many permissions, we can restrict it to minimum.
CAP_NET_BIND_SERVICE can be used to allow this user to bind to a port < 1024 if desired.
The work is based on wireproxy's systemd configuration[1]. Also I found systemd service hardening doc[2] helpful.
DynamicUser/Strict system protection didn't work as package installs forwarder binary at /usr/bin.
[1] https://github.com/pufferffish/wireproxy/pull/103.
[2] https://gist.github.com/ageis/f5595e59b1cddb1513d1b425a323db04
> systemd: restrict permissions

- net.go
- ratelimit/listener.go
This patch pushes the invertion of limits down to the listener constructing code. It fits better here. Users do not have to invert it themselves.
The limit is global.
> ratelimit: invert read and write limits

- dialvia/socks5.go
- dialvia/socks5_test.go
Returned socks dialer has DialContext method, however it is not exported due to backwards compatibility issues.
> dialvia(socks5): support context dialing

- e2e/Makefile
- e2e/setup/runner.go
- utils/compose/cmd.go
This patch set allows to run e2e tests under podman with docker-compose and podman-compose.
> e2e: podman-compose compatibility

- local/monitoring/dashboards/forwarder.json
> local/monitoring: add http req res size graphs

- internal/martian/header/via_modifier.go
- internal/martian/header/via_modifier_test.go
This is to remove hanging connections from http.Transport.
Fixes #688
> martian/header(via): close looped request

- e2e/dns/db.rpz
- e2e/setups.go
As observed in a few CI runs[1] assigning private addresses might result in an overlap with randomly generated networks. Both Podman and Docker assign private addresses (10.0.0.0, 172.16.0.0, 192.168.0.0) when the network is not specified.
This patch changes static IP addresses in dns setups to non-private to minimize the chance of collision.
[1] https://github.com/saucelabs/forwarder/actions/runs/8896336713/job/24428757815
> e2e: change static IPs in dns test

- e2e/Makefile
make up,down,logs would not work with specified COMPOSE_PROJECT_NAME.
> e2e(mk): export compose project name in all targets

- internal/martian/proxy_conn.go
- internal/martian/proxy_test.go
> martian: fix CONNECTs content length 

- internal/martian/flush.go
- internal/martian/flush_test.go
- internal/martian/proxy_conn.go
- internal/martian/proxy_handler.go
- utils/httpbin/sse.go
This patch applies patternFlushWriter to support
- non-chunked SSE i.e. flush after '\n\n'
- chunked-encoding i.e. flush after '\r\n'
> martian: support server sent events without chunked encoding

- bind/flag.go
- docs/content/cli/forwarder_run.md
- docs/content/config/forwarder_run.yaml
```
-H, --header <header> (env FORWARDER_HEADER)
Add or remove HTTP request headers. 
Use the format:
- name:value to add a header
- name; to set the header to empty value
- -name to remove the header
- -name* to remove headers by prefix
The header name will be normalized to canonical form. The header value should not contain any newlines or
carriage returns. The flag can be specified multiple times. The following example removes the User-Agent
header and all headers starting with X-. 
-H "-User-Agent" -H "-X-*"
```
> bind: improve header flag usage with tags

- bind/flag.go
- bind/log.go
- httplog/httplog.go
> bind: fix httplogFlag default value in help

- log/level.go
That would eliminate the zero value issue with flags.
```
--log-level <error|info|debug> (default error) (env FORWARDER_LOG_LEVEL)
Log level.
```
Fixes #832
> log: change level type to string

- internal/martian/copy.go
- internal/martian/proxy_conn.go
- internal/martian/proxy_handler.go
This work is ported from failed #834.
> martian: refactor copySync() for easier bidirectional copying

- http_proxy.go
- middleware/prometheus.go
It can be used to partition the metrics by custom conditions. e.g. Label direct/tunnel mode in SC5.
PrometheusOpt was chosen to ensure compatibility with existing prom instances.
> middleware(prom): add customizable label for http metrics

- e2e/setups.go
- utils/compose/network.go
> e2e: fix invalid ip range 

- log/level.go
The previous idea was wrong. String type messes up the order of log levels.
We will shift it.
> log: revert log level to int

- bind/file.go
- bind/flag.go
Change constructor and export so that ad-hoc anyflag initialization is not needed.
> bind: refactor osFileFlag to FileFlag

- utils/cobrautil/bind.go
> utils/cobrautil: add functional options to BindAll() to allow Viper customization

- bind/flag.go
This prevents config rendering code that can selectively turn off redact from working making redact function permanent.
> chore(bind): make log-file flag redact function permanent

- internal/martian/proxy_conn.go
- internal/martian/proxy_connect.go
- internal/martian/proxy_handler.go
- internal/martian/proxy_test.go
Make sure that we correctly read and send Content-Length header value for CONNECT requests.
> Fix content length in CONNECT requests and responses

- utils/httpbin/httpbin.go
> chore(utils/httpbin): make delay return 200 on contex cancel explicit

- Containerfile
- api.go
- command/ready/ready.go
- command/run/run.go
- command/test/httpbin/httpbin.go
- e2e/forwarder/service.go
- utils/httpx/httpx.go
- utils/httpx/httpx_test.go
This patchset implements checking readiness over a Unix socket.
Unnecessary API servers in e2e tests are removed.
The ready command implementation is extended and improved for better reuse.   
Fixes #873
> Fix reading api-address from config file in container

- net_metrics.go
- net_metrics_test.go
Since 5ca0e4d7afbf790365edd5a40e1bd3b7f23237bc we do not recognize :: as localhost.
Treat unspecified IP address as localhost - for backwards compatibility with isLocalhost(). Optimize common localhost names.
> net: fix addr2Host for backwards compatibility with isLocalhost()

- bind/flag.go
- command/forwarder/root.go
- command/run/run.go
- config.go
- config_test.go
- credentials.go
- e2e/forwarder/service.go
- e2e/run.go
- e2e/setups.go
- e2e/tests/flag_test.go
- host.go
- host_test.go
- net.go
- net_test.go
> Add --connect-to flag that allows to change dial target

- log/stdlog/opts.go
- log/stdlog/stdlog.go
- log/stdlog/stdlog_test.go
I want to be able to modify the sublogger level. It should be possible to pass custom options when creating a sublogger.
> log/stdlog: allow to pass options when creating a sublogger

- proxyproto/testdata/gen.go
Import path was changed by IDE when go:build was added.
> chore(proxyproto/testdata): fix import path

- bind/flag.go
That allows to pass default dns servers to the bind.
> bind: fix passing default value for --dns-server flag

- internal/martian/proxy_handler.go
This improves debugging experience by logging the request id.
> martian: log with request ctx in h2writer

- .golangci.yml
- internal/martian/proxy_test.go
When I was trying to change martian behaviour that needed some tests to be adjusted, I realised they are in a poor condition. This patch introduces a testHelper to add some structure and reuse similar code blocks. That way it reduces around 150 LoC. It also leaves the tests in better shape for further refactors.
> martian(test): implement testHelper pattern

- conntrack/conntrack.go
- conntrack/conntrack_test.go
- go.mod
- go.sum
- internal/martian/closewriter.go
- net.go
- proxyproto/net.go
- proxyproto/net_test.go
- ratelimit/listener.go
Use builder pattern to return implementation with only required features. Use connfu to handle CloseWrite() and ReadFrom() propagation.
> conntrack: add connection tracker wrapper based on connfu

- http_proxy.go
- net.go
- net_metrics.go
- net_test.go
- testdata/TestMultiListenerMetrics.golden.txt
Add HTTPProxyConfig.ExtraListeners and refactor code to work with multiple listeners.
> http proxy: allow multiple listeners

- internal/martian/proxy_conn.go
- internal/martian/proxy_connect.go
- internal/martian/proxy_handler.go
Fixes https://github.com/saucelabs/forwarder/issues/938
> Fix connect response that prevented proper working of websockets in FireFox

- go.mod
- go.sum
This reverts commit f8c4334ba7d59dc585e6ccb9f0216613d67cf38f.
> Revert "build(deps): bump golang.org/x/net from 0.30.0 to 0.31.0"

- e2e/run.go
- e2e/tests/proxy_test.go
- internal/martian/proxy.go
- internal/martian/proxy_conn.go
- internal/martian/proxy_connect.go
- internal/martian/proxy_handler.go
- utils/httpexpect/httpexpect.go
> martian(mitm): fix connect error response propagation

- net_metrics.go
- testdata/TestDialerMetricsErrors.golden.txt
- testdata/TestDialerMetrics_default.golden.txt
- testdata/TestDialerMetrics_traffic.golden.txt
- testdata/TestListenerMetricsAccepted.golden.txt
- testdata/TestListenerMetricsAcceptedWithTLS.golden.txt
- testdata/TestListenerMetricsClosed.golden.txt
- testdata/TestListenerMetricsErrors.golden.txt
- testdata/TestMultiListenerMetrics.golden.txt
> metrics: connections use active instead of closed 

- internal/martian/header/via_modifier.go
- internal/martian/header/via_modifier_test.go
> martian/header: optimized ViaModifier implementation

- http_proxy.go
- middleware/prometheus.go
- middleware/prometheus_test.go
- middleware/testdata/TestPrometheusWrap.golden.txt
It is much more efficient to use summaries than histograms. This would give information on p50, p90 and p99.
Fixes #925
> middleware(prometheus): use summaries instead of histograms

- .golangci.yml
- bind/flag.go
- net.go
- net_metrics.go
- net_test.go
- testdata/TestDialerMetricsRetriesAndErrors.golden.txt
> net: dial retries

- http_proxy_errors.go
- internal/martian/close.go
- internal/martian/copy.go
- internal/martian/errors.go
- internal/martian/proxy_test.go
This will prevent the proxy from leaking connections with defective servers.
Given limited resources, this is the best we can do for #800 right now.
That fix cannot be tested due to https://github.com/saucelabs/forwarder/issues/1013. Enable the test again once that is fixed.
For now I tested it manually.
> martian: add graceful close timeout for bicopy

- httplog/httplog.go
- httplog/httplog_bench_test.go
- httplog/logwriter.go
- httplog/slog.go
Structured http logs will be needed once we migrate to `log/slog`.
> httplog: add structured logger

- http_proxy.go
- tls.go
This change adds a prometheus gauge metric `days_until_cert_expiring` that reports the number of days remaining until a TLS certificate expires. It includes a `cn` and `dns_names` labels to identify the certificate. This enables alerting and helps prevent outages due to expired certificates.
> SC-5230: TLS certificate expiration monitoring

- internal/martian/proxy_conn.go
- internal/martian/proxy_handler.go
- internal/martian/proxy_test.go
traceWroteResponse would be called multiple times when handling CONNECT and protocol upgrade requests.
This patch assures there is exactly one call to wroteResponse per one call to readRequest.
> martian: fix trace wrote response is called once per request

- internal/martian/copy.go
- internal/martian/h2/h2.go
- internal/martian/h2/relay.go
- internal/martian/log/log.go
- internal/martian/log/nop.go
- internal/martian/log/test.go
- internal/martian/mitm/mitm.go
- internal/martian/proxy.go
- internal/martian/proxy_conn.go
- internal/martian/proxy_connect.go
- internal/martian/proxy_handler.go
- internal/martian/proxy_test.go
- internal/martian/trace.go
- log/martianlog/adapter.go
- log/martianlog/dial.go
- log/martianlog/martianlog.go
We are working on introducing a new Sauce Labs logging policy.
This patch brings us a step closer by replacing internal logger interface with a structured one.
> martian: switch to structured logging 

- command/pac/server/server.go
- command/run/run.go
- command/test/grpc/grpc.go
- command/test/httpbin/httpbin.go
- credentials.go
- credentials_test.go
- http_proxy.go
- http_proxy_errors.go
- http_proxy_test.go
- http_server.go
- internal/martian/log/log.go
- internal/martian/log/nop.go
- internal/martian/trace.go
- log/adapter.go
- log/level.go
- log/log.go
- log/martianlog/adapter.go
- log/martianlog/martianlog.go
- log/nop.go
- log/slog/opts.go
- log/slog/slog.go
- pac.go
- utils/cobrautil/describe.go
This patch transitions forwarder logging to a structured one. 
So far there is only `json` mode for production usage, but there will shortly be a `text` mode, that is more human friendly.
This brakes compatibility, so we provided adapter that takes old logger interface and produces a structured one (see `forwarder/log.StrucuredLoggerAdapter`).
> switch to structured logging

- command/pac/server/server.go
- command/run/run.go
- command/test/httpbin/httpbin.go
- log/slog/slog.go
It's not entirely clear what the name attribute refers to.
In my opinion, log would be a better fit—it clearly indicates that it's related to the application's logging module.
> log/slog: rename log name attribute from "name" to "module"

- log/slog/slog.go
It should be made configurable, not hard-coded. Removing for now.
That makes the logs look less heavy:
```
time=2025-07-01T15:44:38.159+02:00 level=INFO msg=Forwarder version=Unknown commit=Unknown
time=2025-07-01T15:44:38.159+02:00 level=INFO msg="using default configuration"
time=2025-07-01T15:44:38.159+02:00 level=INFO msg="no upstream proxy specified" module=proxy
time=2025-07-01T15:44:38.159+02:00 level=INFO msg="proxy localhost" module=proxy mode=deny
time=2025-07-01T15:44:38.160+02:00 level=INFO msg="PROXY server listen" module=proxy address=[::]:3128 protocol=http
time=2025-07-01T15:44:38.163+02:00 level=INFO msg="HTTP server listen" module=api address=127.0.0.1:10000 protocol=http
```
> log/slog: do not use custom sl attribute names
