saucelabs/forwarder

- CHANGELOG.md
- CONTRIBUTION.md
- README.md
> Updating docs

- CHANGELOG.md
- internal/util/util.go
- internal/util/util_test.go
- pkg/proxy/proxy.go
- Detect IPv6 localhost
- Change the logging message
> Improve localhost detection

- cmd/forwarder/run.go
- example_test.go
- proxy.go
- proxy_test.go
- util.go
- validation/validation.go
- validation/validation_test.go
Needs rebase after merging other PR.
This sanitizes Proxy configuration.
> Remove retry port and refactor Proxy configuration

- proxy.go
- proxy_test.go
> Do not expose Proxy internal state

- .golangci.yml
- cert.go
- cert_test.go
- http_server.go
> http server: self signed certificate generation if no certificate is provided

- .golangci.yml
- .goreleaser.yml
- api.go
- cmd/forwarder/proxy/proxy.go
- cmd/forwarder/version/version.go
- internal/version/version.go
- Move version variables to internal/version
- Add /version endpoint
> api: add version

- .goreleaser.yml
- Dockerfile
- Makefile
- cert.go
- cmd/forwarder/proxy/proxy.go
- middleware/basic_auth.go
- packaging/deb/forwarder.postrm
- packaging/deb/forwarder.preinst
- packaging/deb/forwarder.prerm
- packaging/rpm/forwarder.postinst
- packaging/rpm/forwarder.postrm
- packaging/rpm/forwarder.preinst
- packaging/rpm/forwarder.prerm
- packaging/systemd/forwarder.service
> goreleaser: build docker images, DEBs and RPMs

- http_proxy.go
This patch allows extra request and response modifiers to be set in proxy config. 
Extra request modifiers will be executed after the core modifiers. 
Extra response modifiers will be executed before the core modifiers.
Fixes #156
> http_proxy: allow configuring extra request and response modifiers

- cmd/forwarder/version/version.go
- credentials.go
- fileurl/fileurl.go
- http_proxy.go
- log/config.go
- log/stdlog/stdlog.go
- middleware/basic_auth.go
- middleware/logger.go
- pac/netutil.go
> add empty line between header and package

- bind/flag.go
- http_proxy.go
- http_proxy_test.go
> modifiers: add request modifier that removes headers by prefix

- bind/flag.go
- http_proxy.go
- http_server.go
- httplog/logger.go
- middleware/logger.go
This patch adds new http logging modes
> httplog: add new logger

- Makefile
> makefile: add build target

- api.go
- bind/flag.go
- cmd/forwarder/httpbin/httpbin.go
- cmd/forwarder/pacserver/pacserver.go
- cmd/forwarder/proxy/proxy.go
- credentials.go
- go.mod
- go.sum
This patch exposes flags and theirs values through api and logs them in debug mode. 
All the passwords are redacted.
> Expose configuration through api and in debug mode 

- .github/workflows/go.yml
> gh: split build job into multiple jobs

- runctx/runctx.go
With this patch, runctx will unregister all signals once the ctx is done, bringing back their default behaviour. This means, only the first sigterm cancels ctx. The second one exits the process.
This allows user to force exit forwarder.
> Improve stopping forwarder

- http_proxy.go
Callers can benefit from PAC and credentials management offered by the proxy while not using the proxy.
> http proxy: add function to return ProxyFunc used by the proxy

- bind/flag.go
- cmd/forwarder/root.go
- e2e/forwarder/service.go
- e2e/setups.go
- e2e/tests/flag_test.go
- http_error.go
- http_proxy.go
- regex/ruleset.go
- regex/ruleset_test.go
This patch add the functionality to specify which domains should be denied from proxing. 
Please read commit messages for more info.
> deny domains

- bind/flag.go
- httplog/httplog.go
`short-url` mode logs scheme+host+path instead of the full URL
> change http log mode route to short-url

- bind/flag.go
- cmd/forwarder/run/run.go
- dialvia/http.go
- http_proxy.go
- internal/martian/proxy.go
- internal/martian/proxy_test.go
This allows to modify CONNECT request to upstream proxy.
> add `--proxy-header` for managing proxy headers

- packaging/completions.sh
> packaging: add powershell to completions.sh

- .golangci.yml
- internal/martian/proxy.go
> Fix Windows EOF in tunnel treated as error  

- cmd/forwarder/httpbin/httpbin.go
- cmd/forwarder/pac/server/server.go
- cmd/forwarder/run/run.go
- utils/cobrautil/describe.go
- utils/cobrautil/describe_test.go
Usually what we want is bytes.
> utils/cobrautil: make describe return []bytes insted of string

- dial.go
- http_transport.go
NewDialer never fails do not return error.
Config is never read remove cfg field.
> chore(dial): simplify Dialer creation

- ruleset/regexp.go
```
go run ./cmd/forwarder run --direct-domains localhost,-localhost --deny-domains deny,-dontdeny   
2023/11/17 15:34:38.963450 Forwarder Unknown (Unknown)
2023/11/17 15:34:38.963478 configuration
deny-domains=deny,-dontdeny
direct-domains=localhost,-localhost
```
> ruleset: implement string method on RegexpListItem

- bind/flag.go
- command/run/run.go
- e2e/forwarder/service.go
- local/monitoring/README.md
- local/monitoring/dashboards/forwarder.json
The flag provides no value and makes Dashboard and other tools maintenance more complicated.
> remove `--prom-namespace` flag 

- http_proxy_errors.go
Add req.Host for all handled errors like we do in handleDenyError()
> http_proxy_errors: add host information to the message

- log/stdlog/stdlog.go
The Debug logger is useful in tests.
> log/stdlog: add Debug logger

- internal/martian/proxy_handler.go
> martian: fix invalid error printing

- http_proxy.go
- http_server.go
> Close connection after 1h of inactivity

- internal/martian/proxy_conn.go
- internal/martian/proxy_handler.go
> martian: info log CONNECT rejected with status code

- .github/workflows/docs.yml
- .github/workflows/e2e.yml
- .github/workflows/go.yml
- .github/workflows/govulncheck.yml
- .github/workflows/release.yml
> chore(gh): bump actions/checkout to v4

- command/run/run.go
- local/monitoring/Makefile
> Add metrics for GOMEMLIMIT and GOMAXPROCS

- mitm.go
> http_proxy: use mitm-org with in memory generated CA

- httplog/httplog.go
- internal/martian/context.go
- internal/martian/proxy_conn.go
- internal/martian/proxy_handler.go
- internal/martian/trace.go
- middleware/logger.go
- middleware/prometheus.go
> chore(martian): minor refactoring

- .github/workflows/docs.yml
- .github/workflows/e2e.yml
- .github/workflows/go.yml
- .github/workflows/release.yml
> chore(gh): bump setup-go to v5

- cmd/docsgen/docsgen.go
- utils/docsgen/command.go
This makes the functions importable by other projects.
> docsgen: move WriteCommand and WriteDefaultConfig to utils

- docs/Makefile
> docs(mk): add clean target

- command/run/run.go
- dialvia/http.go
- dialvia/socks5.go
- http_proxy.go
- internal/martian/proxy_connect.go
> dialvia: add connect timeout

- .github/workflows/e2e.yml
- e2e/run.go
- utils/compose/service.go
This makes e2e tests run in 4 minutes instead of 6.
> e2e: cpuset per service

- internal/martian/proxy.go
- internal/martian/proxy_conn.go
- internal/martian/proxy_handler.go
> martian: strip X-Martian-Terminate-TLS before connecting

- .golangci.yml
> golangci: silence grpc.Dial deprecated error

- internal/martian/closewriter.go
- internal/martian/closewriter_test.go
> martian: support iterating over not interfaceable fields in asCloseWriter()

- internal/martian/proxy_conn.go
- internal/martian/proxy_handler.go
> martian: extend round trip error log

- CONTRIBUTION.md
I came across that doc and realized it was mostly copy pasted from some other project. This patch removes the statements that don't apply here.
> contribution: cleanse the doc from false statements

- command/run/run.go
- log/stdlog/stdlog.go
> log: add reopen to API

- utils/compose/builder.go
- utils/compose/compose.go
- utils/compose/volume.go
Add support for data sharing using data containers.
> utils/compose: initial support for data containers

- command/pac/server/server.go
- command/run/run.go
- command/test/grpc/grpc.go
- command/test/httpbin/httpbin.go
- utils/cobrautil/describe.go
- utils/cobrautil/describe_test.go
Enable displaying hidden flags that are set.
> utils/cobrautil: FlagsDescriber change field ShowNotChanged to ShowChangedOnly

- internal/martian/proxy_connect.go
> martian: add not nil header in newConnectResponse()

- internal/martian/proxy_conn.go
> martian(mitm): use newConnectResponse()

- log/rotate_unix_test.go
> log: run test only in unix

- http_proxy_errors.go
- http_proxy_test.go
> http_proxy_errors: improve tls errors handling 

- net.go
> net: add TrackTraffic knob to Listener

- http_proxy.go
- http_proxy_test.go
> http proxy: make isLocalhost() case insensitive

- .goreleaser.yml
- README.md
- docs/Makefile
> docs: move website to opensource.saucelabs.com/forwarder/

- bind/flag.go
- go.mod
- go.sum
- http_proxy.go
- http_proxy_metrics.go
- internal/martian/mitm/cache.go
- internal/martian/mitm/mitm.go
- internal/martian/mitm/mitmprom/mitmprom.go
- local/monitoring/Makefile
- mitm.go
> mitm: LRU cache for certificates 

- internal/martian/proxy.go
- log/slog/opts.go
- log/slog/slog.go
> log/slog: minor improvements 

- bind/flag.go
- log/config.go
- log/slog/slog.go
> log: rename mode config field to format
